# Server configuration
server:
  port: ${EUREKA_PORT:8761}

# Spring configuration
spring:
  profiles:
    active: dev

# Security configuration
security:
  basic:
    path: /**
  user:
    name: ${EUREKA_USERNAME:admin}
    password: ${EUREKA_PASSWORD:password}

# Eureka configuration
eureka:
  # Eureka server configuration
  server:
    # Time to wait when syncing empty registry (0 means no wait)
    waitTimeInMsWhenSyncEmpty: 0

  # Eureka instance configuration
  instance:
    hostname: localhost

  # Eureka client configuration
  client:
    # Whether to register this Eureka instance with itself (false because it's the discovery server)
    registerWithEureka: false
    # Whether to fetch the registry information from Eureka (false because it's the discovery server)
    fetchRegistry: false
    serviceUrl:
      # Default zone URL for Eureka service
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Logging configuration
logging:
  pattern:
    # Take the span id and trace id from the Mapped Diagnostic Context (MDC) and put them into the log message.
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# Management configuration for tracing, metrics, and endpoint exposure
management:
  endpoints:
    web:
      exposure:
        include: 'info, health, prometheus'
  tracing:
    sampling:
      # Set trace sampling rate (1.0 = 100% of traces). Adjust based on traffic volume and system capacity.
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}